# Use root/example as user/password credentials
version: '3.1'

services:

  mariadb:
    image: mariadb:10.2
    container_name: mysqlserver
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    logging:
      driver: syslog
      options:
        tag: "{{.DaemonName}}(image={{.ImageName}};name={{.Name}};id={{.ID}})"
    restart: unless-stopped
    ports:
      - "3306:3306"